name: Tests
on:
  push:
    branches:
    - "**"
  pull_request:
    branches:
    - master
jobs:

  node:
    strategy:
      matrix:
        node: [14.x, 15.x]
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: |
        npm install --prefer-offline --no-audit --no-fund
        npm run lint:node
    - working-directory: packages/webpack-config-node
      run: |
        npm install --prefer-offline --no-audit --no-fund
        npm test

  web:
    strategy:
      matrix:
        node: [14.x, 15.x]
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - uses: microsoft/playwright-github-action@v1
    - run: |
        npm install --prefer-offline --no-audit --no-fund
        npm run lint:web
    - working-directory: packages/webpack-config-web
      run: |
        npm install --prefer-offline --no-audit --no-fund
        npm test
