name: Tests
on:
  push:
    branches:
      - '**'
jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:

      - name: Download sources
        uses: actions/checkout@v1

      - name: Use Node LTS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Test Eslint
        run: npm run test:lint

      - name: Test Params
        run: npm run test:params

      - name: Test Assets
        run: npm run test:assets

      - name: Test Clean
        run: npm run test:clean

      - name: Test Core
        run: npm run test:core

      - name: Test CSS
        run: npm run test:css

      - name: Test Optimize
        run: npm run test:optimize

      - name: Test Webworkers
        run: npm run test:webworkers
