name: Tests
on:
    push:
        branches:
            - "**"
    pull_request:
        branches:
            - master
jobs:
    tests:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - name: Download sources
              uses: actions/checkout@v1

            - name: Use Node LTS
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install dependencies
              run: npm install

            - name: Test Eslint
              run: npm run lint

            - name: Test Web Params
              run: npm run test:web-params

            - name: Test Web Assets
              run: npm run test:web-assets

            - name: Test Web Clean
              run: npm run test:web-clean

            - name: Test Web Core
              run: npm run test:web-core

            - name: Test Web CSS
              run: npm run test:web-css

            - name: Test Web Optimize
              run: npm run test:web-optimize

            - name: Test Web Webworkers
              run: npm run test:web-webworkers

