name: Tests
on:
    push:
        branches:
            - "**"
    pull_request:
        branches:
            - master
jobs:
    tests:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - name: Download sources
              uses: actions/checkout@v1

            - name: Use Node LTS
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install dependencies
              run: npm install

            - name: Test Lint
              run: npm run test:lint

            - name: Test Params
              run: npm run test:params

            - name: Test Setup
              run: npm run test:setup

            - name: Test Web
              run: npm run test:web

            - name: Test Node
              run: npm run test:node
