name: Tests
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master
jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run test:lint
      - run: npm run test:params
      - run: npm run test:setup
      - run: npm run test:web
      - run: npm run test:node
